services:
  oxwall:
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8080:80'
    networks:
      - oxwall
    volumes:
      - .:/var/www/html
    depends_on:
      - database
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: testing
    ports:
      - '3306:3306'
    networks:
      - oxwall
    volumes:
      - ow_mysql:/var/lib/mysql
networks:
  oxwall:
volumes:
  ow_mysql:
