services:
  oxwall:
    build:
      dockerfile: ./server.Dockerfile
      args:
        dir_to_copy: 'robots.txt'
    ports:
      - '8080:80'
    networks:
      - oxwall
    volumes:
      - .:/var/www/html
      - ow_mysql:/var/lib/mysql
    depends_on:
      - database
  database:
    image: mysql:latest
    command:
      - '--require_secure_transport=ON'
    environment:
      MYSQL_ROOT_PASSWORD: testing
    ports:
      - '3306:3306'
    networks:
      - oxwall
    volumes:
      - ow_mysql:/var/lib/mysql
networks:
  oxwall:
volumes:
  ow_mysql:
  ow_mysql_tls:
