name: Create Oxwall Release
run-name: Build and publish a new Oxwall release
on:
  push:
    tags:
      '[0-9]+.[0-9]+.[0-9]+'
jobs:
  Create-New-Release:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        uses: php-actions/composer@v6
        with:
          php_version: 8.3
      # - run: ow_libraries/vendor/bin/phpunit ow_unittest
      - run: cd $GITHUB_WORKSPACE
      - run: mv ow_install_default ow_install
      - run: mv ow_includes/config.php.default ow_includes/config.php
      - run: cp .gitignore .gitignore.bak
      - run: sed -i -n '/^# FOR RELEASES:$/q;p' .gitignore
      - run: git add . && git config user.name 'Oxwall Pipeline' && git config user.email '<>'
      - run: git commit -m 'Temporary commit for packaging ignored artifacts'
      - run: git archive HEAD --output oxwall-"${GITHUB_REF##*/}".zip
      - run: mv .gitignore.bak .gitignore
      - name: Package Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            oxwall-*.zip
          token: ${{ secrets.CREATE_RELEASE_TOKEN }}
